Repository opensearch-project/flow-framework, pull requests merged in 2024-04, with the labels that each got.

#632 Warn about escaping quotes in curl command
  sample-templates/README.md
Labels: documentation, backport 2.x, skip-changelog

#636 Moves ui-metadata field from state to template index
  src/main/resources/mappings/global-context.json
  src/main/resources/mappings/workflow-state.json
Labels: skip-changelog

#639 Silently ignore content on APIs that don't require it
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/rest/RestDeleteWorkflowAction.java
  src/main/java/org/opensearch/flowframework/rest/RestDeprovisionWorkflowAction.java
  src/main/java/org/opensearch/flowframework/rest/RestGetWorkflowAction.java
  src/main/java/org/opensearch/flowframework/rest/RestGetWorkflowStateAction.java
  src/main/java/org/opensearch/flowframework/rest/RestGetWorkflowStepAction.java
  src/test/java/org/opensearch/flowframework/rest/RestDeleteWorkflowActionTests.java
  src/test/java/org/opensearch/flowframework/rest/RestDeprovisionWorkflowActionTests.java
  src/test/java/org/opensearch/flowframework/rest/RestGetWorkflowActionTests.java
  src/test/java/org/opensearch/flowframework/rest/RestGetWorkflowStateActionTests.java
  src/test/java/org/opensearch/flowframework/rest/RestGetWorkflowStepActionTests.java
Labels: backport 2.x

#635 Reset workflow state to initial state after successful deprovision
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportAction.java
Labels: backport 2.x

#586 Use jsonB instead of jackson
  build.gradle
  src/main/java/org/opensearch/flowframework/util/ParseUtils.java
  src/test/java/org/opensearch/flowframework/util/ParseUtilsTests.java
Labels: backport 2.x, skip-changelog

#646 Reduce unnecessary duplication of changelog verifier GHA runs
  .github/workflows/changelog_verifier.yml
Labels: backport 2.x, skip-changelog

#642 Improve error messages for workflow states other than NOT_STARTED
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandler.java
  src/main/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportAction.java
  src/test/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandlerTests.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
  src/test/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportActionTests.java
Labels: backport 2.x

#658 Adding guardrails to default use case params
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/common/DefaultUseCases.java
  src/main/java/org/opensearch/flowframework/rest/RestCreateWorkflowAction.java
  src/test/java/org/opensearch/flowframework/FlowFrameworkRestTestCase.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
  src/test/java/org/opensearch/flowframework/rest/RestCreateWorkflowActionTests.java
Labels: backport 2.x

#671 Allow strings for boolean workflow step parameters
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/workflow/AbstractRegisterLocalModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterModelGroupStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterRemoteModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/ToolStep.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalCustomModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalPretrainedModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalSparseEncodingModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterModelGroupStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterRemoteModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/ToolStepTests.java
Labels: backport 2.x

#680 Hides user and credential field from search response
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/rest/AbstractSearchWorkflowAction.java
  src/main/java/org/opensearch/flowframework/transport/GetWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/SearchWorkflowStateTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/SearchWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/util/EncryptorUtils.java
  src/main/java/org/opensearch/flowframework/util/ParseUtils.java
  src/main/java/org/opensearch/flowframework/util/RestHandlerUtils.java
  src/test/java/org/opensearch/flowframework/transport/SearchWorkflowStateTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/SearchWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/util/EncryptorUtilsTests.java
  src/test/java/org/opensearch/flowframework/util/RestHandlerUtilsTests.java
Labels: backport 2.x

#676 Throw the correct error message in status API for WorkflowSteps
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/exception/WorkflowStepException.java
  src/main/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/workflow/AbstractCreatePipelineStep.java
  src/main/java/org/opensearch/flowframework/workflow/AbstractRegisterLocalModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/CreateConnectorStep.java
  src/main/java/org/opensearch/flowframework/workflow/CreateIndexStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteAgentStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteConnectorStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeployModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterAgentStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterModelGroupStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterRemoteModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/UndeployModelStep.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
  src/test/java/org/opensearch/flowframework/workflow/CreateIndexStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalCustomModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalPretrainedModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalSparseEncodingModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterRemoteModelStepTests.java
Labels: backport 2.x

#686 Switched to macos-13
  .github/workflows/CI.yml
  CHANGELOG.md
Labels: backport 2.x

#690 Add release notes for 2.14.0
  release-notes/opensearch-flow-framework.release-notes-2.14.0.0.md
Labels: backport 2.x, skip-changelog

#689 Delete workflow state when template is deleted and no resources exist
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandler.java
  src/main/java/org/opensearch/flowframework/transport/DeleteWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportAction.java
  src/test/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandlerTests.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkSecureRestApiIT.java
  src/test/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportActionTests.java
Labels: backport 2.x
