Repository opensearch-project/flow-framework, pull requests merged in 2024-07, with the labels that each got.

#750 Register system index descriptors through SystemIndexPlugin.getSystemIndexDescriptors
  CHANGELOG.md
  build.gradle
  src/main/java/org/opensearch/flowframework/FlowFrameworkPlugin.java
  src/test/java/org/opensearch/flowframework/FlowFrameworkPluginTests.java
Labels: backport 2.x

#764 Change deprecated Gradle wrapper validation workflow to replacement
  .github/workflows/wrapper.yml
Labels: backport 2.x, CI, skip-changelog

#765 Allow lower NodeJS version on GH runners for security test
  .github/workflows/test_security.yml
Labels: backport 2.x, skip-changelog

#755 Stop duplicate CI runs on branch push by bots
  .github/workflows/CI.yml
  .github/workflows/test_bwc.yml
  .github/workflows/test_security.yml
Labels: backport 2.x, skip-changelog

#763 Add allow_delete parameter to Deprovision API
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/FlowFrameworkPlugin.java
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/common/WorkflowResources.java
  src/main/java/org/opensearch/flowframework/rest/RestDeprovisionWorkflowAction.java
  src/main/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteIndexStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteIngestPipelineStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteSearchPipelineStep.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowProcessSorter.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowStep.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowStepFactory.java
  src/test/java/org/opensearch/flowframework/FlowFrameworkRestTestCase.java
  src/test/java/org/opensearch/flowframework/model/WorkflowValidatorTests.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
  src/test/java/org/opensearch/flowframework/rest/RestDeprovisionWorkflowActionTests.java
  src/test/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteIndexStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteIngestPipelineStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteSearchPipelineStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/WorkflowProcessSorterTests.java
Labels: backport 2.x

#778 Improve Template and WorkflowState builders
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandler.java
  src/main/java/org/opensearch/flowframework/model/Template.java
  src/main/java/org/opensearch/flowframework/model/WorkflowState.java
  src/main/java/org/opensearch/flowframework/transport/CreateWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/GetWorkflowStateResponse.java
  src/main/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/util/EncryptorUtils.java
  src/test/java/org/opensearch/flowframework/model/TemplateTests.java
  src/test/java/org/opensearch/flowframework/model/WorkflowStateTests.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
  src/test/java/org/opensearch/flowframework/transport/CreateWorkflowTransportActionTests.java
Labels: backport 2.x

#794 Switch to arm64 runners on macOS
  .github/workflows/CI.yml
Labels: backport 2.x, skip-changelog

#800 add 2.16 release note
  release-notes/opensearch-flow-framework.release-notes-2.16.0.0.md
Labels: backport 2.x, backport 2.16

#805 Handle Not Found deprovision exceptions as successful deletions
  CHANGELOG.md
  release-notes/opensearch-flow-framework.release-notes-2.16.0.0.md
  src/main/java/org/opensearch/flowframework/workflow/DeleteAgentStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteModelStep.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteAgentStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteModelStepTests.java
Labels: backport 2.x, backport 2.16

#808 update 2.16 release note
  release-notes/opensearch-flow-framework.release-notes-2.16.0.0.md
Labels: backport 2.x, skip-changelog, backport 2.16

#811 Have FlowFrameworkException status recognized by ExceptionsHelper
  CHANGELOG.md
  release-notes/opensearch-flow-framework.release-notes-2.16.0.0.md
  src/main/java/org/opensearch/flowframework/exception/FlowFrameworkException.java
  src/test/java/org/opensearch/flowframework/exception/FlowFrameworkExceptionTests.java
Labels: backport 2.x, backport 2.16
