Repository opensearch-project/flow-framework, pull requests merged in 2024-03, with the labels that each got.

#553 Enable Flow Framework by default
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/common/FlowFrameworkSettings.java
  src/test/java/org/opensearch/flowframework/FlowFrameworkRestTestCase.java
  src/test/java/org/opensearch/flowframework/common/FlowFrameworkSettingsTests.java
Labels: backport 2.x

#551 Add created, updated, and provisioned timestamps to saved template
  .github/workflows/test_bwc.yml
  CHANGELOG.md
  build.gradle
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandler.java
  src/main/java/org/opensearch/flowframework/model/Template.java
  src/main/java/org/opensearch/flowframework/transport/CreateWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/util/EncryptorUtils.java
  src/main/resources/mappings/global-context.json
  src/test/java/org/opensearch/flowframework/bwc/FlowFrameworkBackwardsCompatibilityIT.java
  src/test/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandlerTests.java
  src/test/java/org/opensearch/flowframework/model/TemplateTests.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
  src/test/java/org/opensearch/flowframework/rest/RestCreateWorkflowActionTests.java
  src/test/java/org/opensearch/flowframework/transport/CreateWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/GetWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/WorkflowRequestResponseTests.java
  src/test/java/org/opensearch/flowframework/util/EncryptorUtilsTests.java
  src/test/resources/template/noop.json
Labels: backport 2.x

#559 Fix bug passing params to workflows
  src/main/java/org/opensearch/flowframework/transport/CreateWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowProcessSorter.java
Labels: backport 2.x, skip-changelog

#562 Remove HTTP Host step
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/workflow/HttpHostStep.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowStepFactory.java
  src/test/java/org/opensearch/flowframework/model/WorkflowValidatorTests.java
  src/test/java/org/opensearch/flowframework/workflow/HttpHostStepTests.java
Labels: backport 2.x

#558 Adding create ingest pipeline step
  CHANGELOG.md
  build.gradle
  src/main/java/org/opensearch/flowframework/FlowFrameworkPlugin.java
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/model/WorkflowNode.java
  src/main/java/org/opensearch/flowframework/util/ParseUtils.java
  src/main/java/org/opensearch/flowframework/workflow/CreateConnectorStep.java
  src/main/java/org/opensearch/flowframework/workflow/CreateIngestPipelineStep.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowStepFactory.java
  src/test/java/org/opensearch/flowframework/FlowFrameworkRestTestCase.java
  src/test/java/org/opensearch/flowframework/model/WorkflowValidatorTests.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
  src/test/java/org/opensearch/flowframework/rest/RestGetWorkflowStepActionTests.java
  src/test/java/org/opensearch/flowframework/workflow/CreateIngestPipelineStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/WorkflowProcessSorterTests.java
  src/test/resources/template/ingest-pipeline-template.json
Labels: backport 2.x

#561 Removes unnecessary gradle properties
  gradle.properties
Labels: backport 2.x, skip-changelog

#576 Add skip-changelog label to version bump PRs
  .whitesource
Labels: backport 2.x, skip-changelog

#574 Added Create index workflow step
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/common/WorkflowResources.java
  src/main/java/org/opensearch/flowframework/workflow/CreateIndexStep.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowStepFactory.java
  src/test/java/org/opensearch/flowframework/model/WorkflowValidatorTests.java
  src/test/java/org/opensearch/flowframework/workflow/CreateIndexStepTests.java
Labels: backport 2.x

#583 Adding default use cases
  CHANGELOG.md
  build.gradle
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/common/DefaultUseCases.java
  src/main/java/org/opensearch/flowframework/rest/RestCreateWorkflowAction.java
  src/main/java/org/opensearch/flowframework/transport/WorkflowRequest.java
  src/main/java/org/opensearch/flowframework/util/ParseUtils.java
  src/main/resources/defaults/cohere-embedding-defaults.json
  src/main/resources/defaults/local-sparse-search-defaults.json
  src/main/resources/defaults/open-ai-embedding-defaults.json
  src/main/resources/mappings/deploy-remote-model-template-draft.json
  src/main/resources/mappings/open-ai-defaults.json
  src/main/resources/substitutionTemplates/deploy-model-semantic-search-template-v1.json
  src/main/resources/substitutionTemplates/deploy-remote-model-template-extra-params.json
  src/main/resources/substitutionTemplates/deploy-remote-model-template.json
  src/main/resources/substitutionTemplates/neural-sparse-local-template.json
  src/test/java/org/opensearch/flowframework/FlowFrameworkRestTestCase.java
  src/test/java/org/opensearch/flowframework/common/DefaultUseCasesTests.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
  src/test/java/org/opensearch/flowframework/rest/RestCreateWorkflowActionTests.java
  src/test/java/org/opensearch/flowframework/transport/CreateWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/WorkflowRequestResponseTests.java
  src/test/java/org/opensearch/flowframework/util/ParseUtilsTests.java
Labels: backport 2.x

#590 Adding 2.13 release notes
  release-notes/opensearch-flow-framework.release-notes-2.13.0.0.md
Labels: backport 2.x, skip-changelog

#595 Fixing register agent tests
  src/test/java/org/opensearch/flowframework/workflow/RegisterAgentTests.java
  src/test/resources/template/agent-framework.json
Labels: backport 2.x, skip-changelog, backport 2.13

#594 Resetting changelog
  CHANGELOG.md
Labels: backport 2.x, skip-changelog

#604 Fixing default semantic use case integration test
  src/test/java/org/opensearch/flowframework/FlowFrameworkRestTestCase.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
Labels: backport 2.x, skip-changelog, backport 2.13

#607 Fixing neural search name check for default use case integ test
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
Labels: backport 2.x, skip-changelog, backport 2.13

#614 Fixing ingest pipeline integ test
  src/test/java/org/opensearch/flowframework/FlowFrameworkRestTestCase.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
Labels: backport 2.x, skip-changelog, backport 2.13

#622 Added new Guardrail field for remote model
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/model/WorkflowNode.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterRemoteModelStep.java
Labels: backport 2.x, skip-changelog, backport 2.13

#629 Change Query Assist sample template to use Claude model
  sample-templates/observability-chat-agent-openai-untested.json
  sample-templates/observability-chat-agent-openai-untested.yml
  sample-templates/query-assist-agent-claude-tested.json
  sample-templates/query-assist-agent-claude-tested.yml
Labels: backport 2.x, skip-changelog
