Repository opensearch-project/flow-framework, pull requests merged in 2024-08, with the labels that each got.

#804 Adds reprovision API to support updating search pipelines, ingest pipelines index settings
  CHANGELOG.md
  build.gradle
  src/main/java/org/opensearch/flowframework/FlowFrameworkPlugin.java
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/common/WorkflowResources.java
  src/main/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandler.java
  src/main/java/org/opensearch/flowframework/rest/RestCreateWorkflowAction.java
  src/main/java/org/opensearch/flowframework/transport/CreateWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowAction.java
  src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowRequest.java
  src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/WorkflowRequest.java
  src/main/java/org/opensearch/flowframework/util/ParseUtils.java
  src/main/java/org/opensearch/flowframework/workflow/AbstractUpdatePipelineStep.java
  src/main/java/org/opensearch/flowframework/workflow/UpdateIndexStep.java
  src/main/java/org/opensearch/flowframework/workflow/UpdateIngestPipelineStep.java
  src/main/java/org/opensearch/flowframework/workflow/UpdateSearchPipelineStep.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowDataStep.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowProcessSorter.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowStepFactory.java
  src/test/java/org/opensearch/flowframework/FlowFrameworkPluginTests.java
  src/test/java/org/opensearch/flowframework/model/ResourceCreatedTests.java
  src/test/java/org/opensearch/flowframework/model/WorkflowValidatorTests.java
  src/test/java/org/opensearch/flowframework/rest/RestCreateWorkflowActionTests.java
  src/test/java/org/opensearch/flowframework/transport/CreateWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/ReprovisionWorkflowRequestTests.java
  src/test/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/WorkflowRequestResponseTests.java
  src/test/java/org/opensearch/flowframework/util/ParseUtilsTests.java
  src/test/java/org/opensearch/flowframework/workflow/UpdateIndexStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/UpdateIngestPipelineStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/UpdateSearchPipelineStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/WorkflowDataStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/WorkflowProcessSorterTests.java
Labels: backport 2.x

#796 Refactor workflow step resource updates to eliminate duplication
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandler.java
  src/main/java/org/opensearch/flowframework/workflow/AbstractCreatePipelineStep.java
  src/main/java/org/opensearch/flowframework/workflow/AbstractRegisterLocalModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/AbstractRetryableWorkflowStep.java
  src/main/java/org/opensearch/flowframework/workflow/CreateConnectorStep.java
  src/main/java/org/opensearch/flowframework/workflow/CreateIndexStep.java
  src/main/java/org/opensearch/flowframework/workflow/CreateIngestPipelineStep.java
  src/main/java/org/opensearch/flowframework/workflow/CreateSearchPipelineStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeployModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/NoOpStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterAgentStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterModelGroupStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterRemoteModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/ReindexStep.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowData.java
  src/test/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandlerTests.java
  src/test/java/org/opensearch/flowframework/workflow/CreateConnectorStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/CreateIndexStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/CreateIngestPipelineStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/CreateSearchPipelineStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeployModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/NoOpStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterAgentTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalCustomModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalPretrainedModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalSparseEncodingModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterModelGroupStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterRemoteModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/ReindexStepTests.java
Labels: backport 2.x

#834 Adding reprovision integration tests
  src/main/java/org/opensearch/flowframework/model/Template.java
  src/main/java/org/opensearch/flowframework/rest/RestCreateWorkflowAction.java
  src/main/java/org/opensearch/flowframework/util/ParseUtils.java
  src/main/java/org/opensearch/flowframework/workflow/UpdateIndexStep.java
  src/test/java/org/opensearch/flowframework/FlowFrameworkRestTestCase.java
  src/test/java/org/opensearch/flowframework/TestHelpers.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
  src/test/java/org/opensearch/flowframework/rest/RestCreateWorkflowActionTests.java
  src/test/java/org/opensearch/flowframework/util/ParseUtilsTests.java
  src/test/java/org/opensearch/flowframework/workflow/UpdateIndexStepTests.java
  src/test/resources/template/registerremotemodel-createindex.json
  src/test/resources/template/registerremotemodel-ingestpipeline-createindex.json
  src/test/resources/template/registerremotemodel-ingestpipeline-updateindex.json
  src/test/resources/template/registerremotemodel-ingestpipeline.json
  src/test/resources/template/registerremotemodel.json
Labels: backport 2.x, skip-changelog

#838 Added user level access control based on backend roles
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/FlowFrameworkPlugin.java
  src/main/java/org/opensearch/flowframework/common/FlowFrameworkSettings.java
  src/main/java/org/opensearch/flowframework/transport/CreateWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/DeleteWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/GetWorkflowStateTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/GetWorkflowStepTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/GetWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/SearchWorkflowStateTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/SearchWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/handler/SearchHandler.java
  src/main/java/org/opensearch/flowframework/util/ParseUtils.java
  src/main/java/org/opensearch/flowframework/util/RestHandlerUtils.java
  src/test/java/org/opensearch/flowframework/FlowFrameworkPluginTests.java
  src/test/java/org/opensearch/flowframework/FlowFrameworkRestTestCase.java
  src/test/java/org/opensearch/flowframework/TestHelpers.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkSecureRestApiIT.java
  src/test/java/org/opensearch/flowframework/transport/CreateWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/DeleteWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/GetWorkflowStateTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/GetWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/SearchWorkflowStateTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/SearchWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/handler/SearchHandlerTests.java
  src/test/java/org/opensearch/flowframework/util/ParseUtilsTests.java
Labels: backport 2.x, v2.17.0
