Repository opensearch-project/flow-framework, pull requests merged in 2024-09, with the labels that each got.

#853 Add 2.17.0 Release Notes
  release-notes/opensearch-flow-framework.release-notes-2.17.0.0.md
Labels: backport 2.x, skip-changelog, backport 2.17

#859 Fix and Refactor Test with Builder Pattern for Issue #2825
  src/test/java/org/opensearch/flowframework/workflow/DeployModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalCustomModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalPretrainedModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalSparseEncodingModelStepTests.java
Labels: backport 2.x, skip-changelog, backport 2.17

#863 Reset CHANGELOG for next release
  CHANGELOG.md
Labels: backport 2.x

#874 Sample template: add for knowledge base alert analysis agent
  CHANGELOG.md
  sample-templates/create-knowledge-base-alert-agent.json
  sample-templates/create-knowledge-base-alert-agent.yml
Labels: backport 2.x

#880 Quick fix for flaky integ test reprovisioning before template update
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
Labels: backport 2.x, skip-changelog, backport 2.17

#884 2.17.1 Release Notes
  release-notes/opensearch-flow-framework.release-notes-2.17.1.0.md
Labels: backport 2.x, backport main

#875 Add query assist data summary agent template
  CHANGELOG.md
  sample-templates/query-assist-data-summary-agent-claude-tested.json
  sample-templates/query-assist-data-summary-agent-claude-tested.yml
Labels: backport 2.x

#873 Add alert summary agent template
  CHANGELOG.md
  sample-templates/alert-summary-agent-claude-tested.json
  sample-templates/alert-summary-agent-claude-tested.yml
Labels: backport 2.x
