Repository opensearch-project/flow-framework, pull requests merged in 2024-10, with the labels that each got.

#894 Update workflow state without using painless script
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandler.java
  src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java
  src/test/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandlerTests.java
  src/test/java/org/opensearch/flowframework/transport/CreateWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportActionTests.java
Labels: backport 2.x

#893 [Backport 2.x] update dependency com.amazonaws:aws-encryption-sdk-java and dependencies
  build.gradle
Labels: skip-changelog

#900 Add ApiSpecFetcher for Fetching and Comparing API Specifications
  CHANGELOG.md
  build.gradle
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/exception/ApiSpecParseException.java
  src/main/java/org/opensearch/flowframework/util/ApiSpecFetcher.java
  src/test/java/org/opensearch/flowframework/exception/ApiSpecParseExceptionTests.java
  src/test/java/org/opensearch/flowframework/util/ApiSpecFetcherTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterAgentTests.java
Labels: backport 2.x

#898 Incrementally remove resources from workflow state during deprovisioning
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandler.java
  src/main/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportAction.java
  src/test/java/org/opensearch/flowframework/FlowFrameworkRestTestCase.java
  src/test/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandlerTests.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
  src/test/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportActionTests.java
Labels: backport 2.x

#911 Force tests jackson dependencies to 2.18
  build.gradle
Labels: backport 2.x, skip-changelog

#899 Add optional config field to tool step
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/workflow/ToolStep.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowStepFactory.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterAgentTests.java
  src/test/java/org/opensearch/flowframework/workflow/ToolStepTests.java
Labels: backport 2.x

#918 Fixed Template Update Location and Improved Logger Statements in ReprovisionWorkflowTransportAction
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java
Labels: backport 2.x

#928 Add 2.18.0 release notes
  release-notes/opensearch-flow-framework.release-notes-2.18.0.0.md
Labels: backport 2.x, skip-changelog, v2.18.0

#924 Add backport failed label when backport fails
  .github/workflows/backport.yml
Labels: backport 2.x, skip-changelog

#930 Revert PR #880: Remove temporary fix for integration tests
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
Labels: backport 2.x, skip-changelog
