Repository opensearch-project/flow-framework, pull requests merged in 2024-02, with the labels that each got.

#494 Make sure retryableGetMlTask evaluates task response at least once
  src/main/java/org/opensearch/flowframework/workflow/AbstractRetryableWorkflowStep.java
Labels: backport 2.x, skip-changelog

#497 Add env varibale to fix codecov
  .github/workflows/CI.yml
Labels: backport 2.x, skip-changelog

#504 Redacting credentials from Get Workflows and Search Workflows API
  src/main/java/org/opensearch/flowframework/rest/AbstractSearchWorkflowAction.java
  src/main/java/org/opensearch/flowframework/transport/GetWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/util/EncryptorUtils.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
  src/test/java/org/opensearch/flowframework/transport/GetWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/util/EncryptorUtilsTests.java
Labels: backport 2.x, skip-changelog, backport 2.12

#498 Add sample templates
  sample-templates/README.md
  sample-templates/deploy-bedrock-claude-model.json
  sample-templates/deploy-bedrock-claude-model.yml
  sample-templates/deploy-openai-model.json
  sample-templates/deploy-openai-model.yml
  sample-templates/deploy-sagemaker-mistral-model.json
  sample-templates/deploy-sagemaker-mistral-model.yml
  sample-templates/observability-chat-agent.json
  sample-templates/observability-chat-agent.yml
  sample-templates/query-assist-agent.json
  sample-templates/query-assist-agent.yml
Labels: backport 2.x, skip-changelog

#509 Throw FlowFrameworkException instead of IOException on parsing errors
  src/main/java/org/opensearch/flowframework/model/PipelineProcessor.java
  src/main/java/org/opensearch/flowframework/model/Template.java
  src/main/java/org/opensearch/flowframework/model/Workflow.java
  src/main/java/org/opensearch/flowframework/model/WorkflowEdge.java
  src/main/java/org/opensearch/flowframework/model/WorkflowNode.java
  src/main/java/org/opensearch/flowframework/model/WorkflowState.java
  src/main/java/org/opensearch/flowframework/model/WorkflowStepValidator.java
  src/test/java/org/opensearch/flowframework/model/PipelineProcessorTests.java
  src/test/java/org/opensearch/flowframework/model/TemplateTests.java
  src/test/java/org/opensearch/flowframework/model/WorkflowEdgeTests.java
  src/test/java/org/opensearch/flowframework/model/WorkflowNodeTests.java
  src/test/java/org/opensearch/flowframework/model/WorkflowStepValidatorTests.java
  src/test/java/org/opensearch/flowframework/model/WorkflowValidatorTests.java
  src/test/java/org/opensearch/flowframework/workflow/WorkflowProcessSorterTests.java
Labels: backport 2.x, skip-changelog, backport 2.12

#514 Ensure params are consumed before checking feature flag
  src/main/java/org/opensearch/flowframework/rest/RestCreateWorkflowAction.java
  src/main/java/org/opensearch/flowframework/rest/RestGetWorkflowStateAction.java
Labels: backport 2.x, skip-changelog, backport 2.12

#515 Improve provisioning exceptions with step ID and hide exception details
  src/main/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandler.java
  src/main/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportAction.java
Labels: backport 2.x, skip-changelog, backport 2.12

#520 Update README and Developer Guide
  DEVELOPER_GUIDE.md
  README.md
Labels: backport 2.x, skip-changelog

#527 Fixed response of Deploy Model Step
  DEVELOPER_GUIDE.md
  src/main/java/org/opensearch/flowframework/workflow/DeployModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowStepFactory.java
  src/main/resources/mappings/workflow-steps.json
  src/test/java/org/opensearch/flowframework/FlowFrameworkRestTestCase.java
  src/test/java/org/opensearch/flowframework/workflow/DeployModelStepTests.java
Labels: backport 2.x, skip-changelog

#523 Moved workflow-steps.json to Enum
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/model/WorkflowStepValidator.java
  src/main/java/org/opensearch/flowframework/model/WorkflowValidator.java
  src/main/java/org/opensearch/flowframework/transport/GetWorkflowStepResponse.java
  src/main/java/org/opensearch/flowframework/transport/GetWorkflowStepTransportAction.java
  src/main/java/org/opensearch/flowframework/workflow/ToolStep.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowProcessSorter.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowStepFactory.java
  src/main/resources/mappings/workflow-steps.json
  src/test/java/org/opensearch/flowframework/model/WorkflowStepValidatorTests.java
  src/test/java/org/opensearch/flowframework/model/WorkflowValidatorTests.java
  src/test/java/org/opensearch/flowframework/transport/GetWorkflowStepTransportActionTests.java
  src/test/java/org/opensearch/flowframework/workflow/WorkflowProcessSorterTests.java
Labels: backport 2.x

#532 Fixed static fields initialization in WorkflowStepFactory
  src/main/java/org/opensearch/flowframework/FlowFrameworkPlugin.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowStepFactory.java
  src/test/java/org/opensearch/flowframework/model/WorkflowValidatorTests.java
  src/test/java/org/opensearch/flowframework/workflow/WorkflowProcessSorterTests.java
Labels: backport 2.x, skip-changelog

#530 Add an HttpHost Workflow Step
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/workflow/HttpHostStep.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowStepFactory.java
  src/test/java/org/opensearch/flowframework/model/WorkflowValidatorTests.java
  src/test/java/org/opensearch/flowframework/workflow/HttpHostStepTests.java
Labels: backport 2.x

#538 Added an optional workflow_step param to the get workflow steps API
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/rest/RestGetWorkflowStepAction.java
  src/main/java/org/opensearch/flowframework/transport/GetWorkflowStepTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/WorkflowRequest.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowStepFactory.java
  src/test/java/org/opensearch/flowframework/rest/RestGetWorkflowStepActionTests.java
  src/test/java/org/opensearch/flowframework/transport/GetWorkflowStepTransportActionTests.java
Labels: backport 2.x

#543 Don't fail create workflow on already-consumed OpenSearch REST params
  src/main/java/org/opensearch/flowframework/rest/RestCreateWorkflowAction.java
  src/test/java/org/opensearch/flowframework/rest/RestCreateWorkflowActionTests.java
Labels: backport 2.x, skip-changelog

#524 Refactored logging for consistency
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/indices/FlowFrameworkIndicesHandler.java
  src/main/java/org/opensearch/flowframework/model/Template.java
  src/main/java/org/opensearch/flowframework/model/WorkflowStepValidator.java
  src/main/java/org/opensearch/flowframework/model/WorkflowValidator.java
  src/main/java/org/opensearch/flowframework/rest/RestCreateWorkflowAction.java
  src/main/java/org/opensearch/flowframework/rest/RestDeleteWorkflowAction.java
  src/main/java/org/opensearch/flowframework/rest/RestDeprovisionWorkflowAction.java
  src/main/java/org/opensearch/flowframework/rest/RestGetWorkflowAction.java
  src/main/java/org/opensearch/flowframework/rest/RestGetWorkflowStateAction.java
  src/main/java/org/opensearch/flowframework/rest/RestGetWorkflowStepAction.java
  src/main/java/org/opensearch/flowframework/rest/RestProvisionWorkflowAction.java
  src/main/java/org/opensearch/flowframework/transport/CreateWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/DeleteWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/GetWorkflowStateTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/GetWorkflowStepTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/GetWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/SearchWorkflowStateTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/SearchWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/util/EncryptorUtils.java
  src/main/java/org/opensearch/flowframework/workflow/AbstractRegisterLocalModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/AbstractRetryableWorkflowStep.java
  src/main/java/org/opensearch/flowframework/workflow/CreateConnectorStep.java
  src/main/java/org/opensearch/flowframework/workflow/CreateIndexStep.java
  src/main/java/org/opensearch/flowframework/workflow/CreateIngestPipelineStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteAgentStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteConnectorStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeployModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterAgentStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterModelGroupStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterRemoteModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/UndeployModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowStepFactory.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkSecureRestApiIT.java
  src/test/java/org/opensearch/flowframework/transport/CreateWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/DeleteWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/GetWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/util/EncryptorUtilsTests.java
  src/test/java/org/opensearch/flowframework/workflow/CreateIngestPipelineStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteAgentStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteConnectorStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeployModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalCustomModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalPretrainedModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalSparseEncodingModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterRemoteModelStepTests.java
Labels: backport 2.x
