Repository opensearch-project/flow-framework, pull requests merged in 2024-06, with the labels that each got.

#721 Added a new parse util method to avoid repetition / refactored code with new method
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/util/ParseUtils.java
  src/main/java/org/opensearch/flowframework/workflow/AbstractRegisterLocalModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterModelGroupStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterRemoteModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/ToolStep.java
  src/test/java/org/opensearch/flowframework/util/ParseUtilsTests.java
Labels: backport 2.x

#732 Added conversation search default use case with RAG tool
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/common/DefaultUseCases.java
  src/main/resources/defaults/conversational-search-rag-tool-defaults.json
  src/main/resources/substitutionTemplates/conversational-search-with-bedrock-rag-tool-template.json
  src/main/resources/substitutionTemplates/conversational-search-with-cohere-model-template.json
Labels: backport 2.x

#733 Change snapshot workflow jdk to 21
  .github/workflows/publish-snapshots.yml
Labels: backport 2.x, skip-changelog

#738 Adding 2.15 release notes
  CHANGELOG.md
  release-notes/opensearch-flow-framework.release-notes-2.15.0.0.md
Labels: backport 2.x, backport 2.15

#743 remove hits check on e2e test
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
Labels: backport 2.x, skip-changelog, backport 2.15
