Repository opensearch-project/flow-framework, pull requests merged in 2025-07, with the labels that each got.

#1175 bump swaggerversion dependency
  build.gradle
Labels: skip-changelog

#1185 Fix ApiSpecFetcher Memory Issues and Exception Handling
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/util/ApiSpecFetcher.java
  src/test/java/org/opensearch/flowframework/util/ApiSpecFetcherTests.java
Labels: backport 2.19

#1193 Add release notes for 2.19.3
  CHANGELOG.md
  release-notes/opensearch-flow-framework.release-notes-2.19.3.0.md
Labels: documentation

#1195 Add Apache commons-text as we can't access ML Commons plugin classpath
  build.gradle
Labels: skip-changelog, v3.2.0

#1200 Avoid race condition setting encryption key
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/util/EncryptorUtils.java
  src/test/java/org/opensearch/flowframework/util/EncryptorUtilsTests.java
Labels: backport 2.19
