Repository opensearch-project/flow-framework, pull requests merged in 2025-02, with the labels that each got.

#1036 Add Release Notes for 2.19.0
  CHANGELOG.md
  release-notes/opensearch-flow-framework.release-notes-2.19.0.0.md
Labels: backport 2.x, backport 2.19

#1041 Passing tenantId to mlclient getTask for multiTenancy feature
  src/main/java/org/opensearch/flowframework/workflow/AbstractRetryableWorkflowStep.java
  src/test/java/org/opensearch/flowframework/workflow/DeployModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalCustomModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalPretrainedModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalSparseEncodingModelStepTests.java
Labels: bug, backport 2.x, skip-changelog, v2.19.0, backport 2.19

#1045 Fixing unit tests related to mlclient getTask and adding integration test for workflow provisioning under multitenancy
  build.gradle
  src/test/java/org/opensearch/flowframework/FlowFrameworkTenantAwareRestTestCase.java
  src/test/java/org/opensearch/flowframework/rest/FlowFrameworkRestApiIT.java
  src/test/java/org/opensearch/flowframework/rest/RestWorkflowStateTenantAwareIT.java
  src/test/java/org/opensearch/flowframework/workflow/DeployModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalCustomModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalPretrainedModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalSparseEncodingModelStepTests.java
  src/test/resources/template/createconnector-registerremotemodel-deploymodel.json
Labels: backport 2.x, skip-changelog

#1021 Update template for alert summary with new log pattern tools
  CHANGELOG.md
  sample-templates/alert-summary-log-pattern-agent.json
  sample-templates/alert-summary-log-pattern-agent.yml
Labels: backport 2.x

#1058 Move CHANGLOG to 2.x
  CHANGELOG.md
Labels: backport 2.x

#1051 1050: Reduce build warnings.
  formatter/formatting.gradle
  src/main/java/org/opensearch/flowframework/util/ApiSpecFetcher.java
  src/main/java/org/opensearch/flowframework/util/EncryptorUtils.java
  src/main/java/org/opensearch/flowframework/util/TenantAwareHelper.java
  src/main/java/org/opensearch/flowframework/util/WorkflowTimeoutUtility.java
Labels: backport 2.x, skip-changelog

#1067 Use string-based version parsing to improve portability
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowRequest.java
  src/main/java/org/opensearch/flowframework/transport/WorkflowRequest.java
  src/main/java/org/opensearch/flowframework/transport/WorkflowResponse.java
Labels: backport 2.x
