Repository opensearch-project/flow-framework, pull requests merged in 2025-01, with the labels that each got.

#995 Fix tests to handle ambiguous mlClient method signature
  src/test/java/org/opensearch/flowframework/workflow/DeleteConnectorStepTests.java
Labels: backport 2.x, skip-changelog

#999 Fixed the CI action failures due to AL2 with older glibc
  .github/workflows/test_security.yml
Labels: skip-changelog

#990 Add synchronous execution option to workflow provisioning
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/rest/RestCreateWorkflowAction.java
  src/main/java/org/opensearch/flowframework/rest/RestProvisionWorkflowAction.java
  src/main/java/org/opensearch/flowframework/transport/CreateWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowRequest.java
  src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/WorkflowRequest.java
  src/main/java/org/opensearch/flowframework/transport/WorkflowResponse.java
  src/main/java/org/opensearch/flowframework/util/WorkflowTimeoutUtility.java
  src/test/java/org/opensearch/flowframework/rest/RestCreateWorkflowActionTests.java
  src/test/java/org/opensearch/flowframework/rest/RestProvisionWorkflowActionTests.java
  src/test/java/org/opensearch/flowframework/transport/CreateWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/ReprovisionWorkflowRequestTests.java
  src/test/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/WorkflowRequestResponseTests.java
  src/test/java/org/opensearch/flowframework/util/WorkflowTimeoutUtilityTests.java
Labels: backport 2.x

#997 Change Jackson dependency to get version from core to avoid jar hell
  build.gradle
Labels: backport 2.x, skip-changelog

#998 Fixed RBAC fetching from workflow state when template is not present
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/transport/CreateWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/DeleteWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/GetWorkflowStateTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/GetWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/util/ParseUtils.java
  src/test/java/org/opensearch/flowframework/FlowFrameworkRestTestCase.java
Labels: backport 2.x

#1009 [backport 2.x] Add synchronous execution option to workflow provisioning(#990)
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/rest/RestCreateWorkflowAction.java
  src/main/java/org/opensearch/flowframework/rest/RestProvisionWorkflowAction.java
  src/main/java/org/opensearch/flowframework/transport/CreateWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowRequest.java
  src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/WorkflowRequest.java
  src/main/java/org/opensearch/flowframework/transport/WorkflowResponse.java
  src/main/java/org/opensearch/flowframework/util/WorkflowTimeoutUtility.java
  src/test/java/org/opensearch/flowframework/rest/RestCreateWorkflowActionTests.java
  src/test/java/org/opensearch/flowframework/rest/RestProvisionWorkflowActionTests.java
  src/test/java/org/opensearch/flowframework/transport/CreateWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/ReprovisionWorkflowRequestTests.java
  src/test/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/WorkflowRequestResponseTests.java
  src/test/java/org/opensearch/flowframework/util/WorkflowTimeoutUtilityTests.java
Labels: backport 2.x

#1015 [Backport 2.x] Change Jackson dependency to get version from core to avoid jar hell (#997)
  build.gradle
Labels: skip-changelog

#1012 Integrate multitenancy into workflow provisioning
  src/main/java/org/opensearch/flowframework/transport/CreateWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java
  src/main/java/org/opensearch/flowframework/workflow/AbstractCreatePipelineStep.java
  src/main/java/org/opensearch/flowframework/workflow/AbstractRegisterLocalModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/AbstractUpdatePipelineStep.java
  src/main/java/org/opensearch/flowframework/workflow/CreateConnectorStep.java
  src/main/java/org/opensearch/flowframework/workflow/CreateIndexStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteAgentStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteConnectorStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteIndexStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteIngestPipelineStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteSearchPipelineStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeployModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/NoOpStep.java
  src/main/java/org/opensearch/flowframework/workflow/ProcessNode.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterAgentStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterModelGroupStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterRemoteModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/ReindexStep.java
  src/main/java/org/opensearch/flowframework/workflow/ToolStep.java
  src/main/java/org/opensearch/flowframework/workflow/UndeployModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/UpdateIndexStep.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowDataStep.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowProcessSorter.java
  src/main/java/org/opensearch/flowframework/workflow/WorkflowStep.java
  src/test/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportActionTests.java
  src/test/java/org/opensearch/flowframework/workflow/CreateConnectorStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/CreateIndexStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/CreateIngestPipelineStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/CreateSearchPipelineStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteAgentStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteConnectorStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteIndexStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteIngestPipelineStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteSearchPipelineStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeployModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/NoOpStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/ProcessNodeTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterAgentTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalCustomModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalPretrainedModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterLocalSparseEncodingModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterModelGroupStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterRemoteModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/ReindexStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/ToolStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/UndeployModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/UpdateIndexStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/UpdateIngestPipelineStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/UpdateSearchPipelineStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/WorkflowDataStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/WorkflowProcessSorterTests.java
Labels: backport 2.x, skip-changelog

#1020 Passing tenantId to MLClient for Connector, Model and ModelGroup
  src/main/java/org/opensearch/flowframework/workflow/CreateConnectorStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteConnectorStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeleteModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterModelGroupStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterRemoteModelStep.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteConnectorStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteModelStepTests.java
Labels: backport 2.x, skip-changelog

#1028 Passing tenantId to MLClient for Model and Agent Steps
  src/main/java/org/opensearch/flowframework/workflow/DeleteAgentStep.java
  src/main/java/org/opensearch/flowframework/workflow/DeployModelStep.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterAgentStep.java
  src/main/java/org/opensearch/flowframework/workflow/UndeployModelStep.java
  src/test/java/org/opensearch/flowframework/workflow/DeleteAgentStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/DeployModelStepTests.java
  src/test/java/org/opensearch/flowframework/workflow/UndeployModelStepTests.java
Labels: backport 2.x, skip-changelog

#1031 Fixing integ tests due to missing opensearch-job-scheduler plugin
  build.gradle
Labels: backport 2.x, skip-changelog
