Repository opensearch-project/flow-framework, pull requests merged in 2025-05, with the labels that each got.

#1134 Allow maven to publish to all versions
  .github/workflows/publish-snapshots.yml
Labels: enhancement, skip-changelog, release, backport 3.0

#1133 Add Junwei Dai as a maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#1145 Add required dependencies for ML Client
  build.gradle
Labels: skip-changelog

#1139 Make thread pool sizes configurable
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/FlowFrameworkPlugin.java
  src/main/java/org/opensearch/flowframework/common/FlowFrameworkSettings.java
  src/test/java/org/opensearch/flowframework/FlowFrameworkPluginTests.java
  src/test/java/org/opensearch/flowframework/common/FlowFrameworkSettingsTests.java
Labels: v3.1.0

#1141 Conditionally include ddb-client dependency only if env variable set
  .github/workflows/CI.yml
  CHANGELOG.md
  build.gradle
Labels: v3.1.0

#1151 Fixing llm field processing in RegisterAgentStep
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/common/CommonValue.java
  src/main/java/org/opensearch/flowframework/model/WorkflowNode.java
  src/main/java/org/opensearch/flowframework/workflow/RegisterAgentStep.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterAgentTests.java
  src/test/resources/template/agent-framework.json
Labels: v3.1.0

#1155 Pass llm spec params to builder
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/workflow/RegisterAgentStep.java
  src/test/java/org/opensearch/flowframework/workflow/RegisterAgentTests.java
Labels: v3.1.0, v2.19.3

#1154 Include exception type in WorkflowState error field even if no cause
  CHANGELOG.md
  src/main/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportAction.java
  src/test/java/org/opensearch/flowframework/transport/ProvisionWorkflowTransportActionTests.java
Labels: backport 2.19
